import { Subject, UserData } from "@/types";

const user1Subjects: Subject[] = [
  {
    code: "21CSE372P",
    title: "Mastering Cloud Data Services and Analytics with AWS, Azure, and GCP",
    credits: 3,
    ciaMax: 100,
    type: "graded",
    conducted: 47,
    absent: 1,
    components: [
      { name: "FP-I", obtained: 7.2, max: 10 },
      { name: "PBL-I", obtained: 19.5, max: 20 },
      { name: "PBL-II", obtained: 20.0, max: 20 },
    ],
  },
  {
    code: "21CSC303J",
    title: "Software Engineering and Project Management",
    credits: 3,
    ciaMax: 60,
    type: "graded",
    conducted: 38,
    absent: 2,
    components: [
      { name: "FJ-I", obtained: 11.7, max: 15 },
      { name: "FJ-II", obtained: 12.0, max: 15 },
      { name: "FJ-III", obtained: 0.0, max: 15 },
      { name: "LLJ-I", obtained: 7.0, max: 7 },
    ],
  },
  {
    code: "21CSC316J",
    title: "Cloud Architecture and Protocols",
    credits: 3,
    ciaMax: 60,
    type: "graded",
    conducted: 38,
    absent: 4,
    components: [
      { name: "FJ-I", obtained: 12.5, max: 15 },
      { name: "FJ-II", obtained: 10.0, max: 15 },
      { name: "LLJ-I", obtained: 6.8, max: 7 },
    ],
  },
  {
    code: "21IPE317J",
    title: "Advanced AI Cinematics and Virtual Production Engineering",
    credits: 3,
    ciaMax: 60,
    type: "graded",
    conducted: 16,
    absent: 2,
    components: [
      { name: "FJ-I", obtained: 12.3, max: 15 },
      { name: "FJ-II", obtained: 14.0, max: 15 },
      { name: "LLJ-I", obtained: 5.4, max: 7 },
    ],
  },
  {
    code: "21CSS303T",
    title: "Data Science",
    credits: 2,
    ciaMax: 60,
    type: "graded",
    conducted: 26,
    absent: 0,
    components: [
      { name: "FT-I", obtained: 4.5, max: 5 },
      { name: "FT-II", obtained: 10.5, max: 15 },
      { name: "FT-III", obtained: 14.0, max: 15 },
    ],
  },
  {
    code: "21NTO304T",
    title: "Environmental Nanotechnology",
    credits: 3,
    ciaMax: 60,
    type: "graded",
    conducted: 39,
    absent: 3,
    components: [
      { name: "FT-I", obtained: 5.0, max: 5 },
      { name: "FT-II", obtained: 9.6, max: 15 },
      { name: "FT-III", obtained: 10.5, max: 15 },
    ],
  },
  {
    code: "21LEM302T",
    title: "Indian Traditional Knowledge",
    credits: 0,
    ciaMax: 100,
    type: "graded",
    conducted: 6,
    absent: 0,
    components: [
      { name: "FML-I", obtained: 30.0, max: 30 },
      { name: "FML-II", obtained: 28.0, max: 30 },
    ],
  },
  {
    code: "21CSP302L",
    title: "Project",
    credits: 3,
    ciaMax: 100,
    type: "graded",
    conducted: 20,
    absent: 2,
    components: [
      { name: "R-I", obtained: 28.0, max: 30 },
      { name: "R-II", obtained: 40.0, max: 40 },
    ],
  },
  {
    code: "21IPE317J-P",
    title: "Advanced AI Cinematics and Virtual Production Engineering (Lab)",
    credits: 0,
    ciaMax: 60,
    type: "attend-only",
    conducted: 22,
    absent: 0,
    components: [],
  },
  {
    code: "21CSC303J-P",
    title: "Software Engineering and Project Management (Lab)",
    credits: 0,
    ciaMax: 60,
    type: "attend-only",
    conducted: 26,
    absent: 0,
    components: [],
  },
  {
    code: "21CSC316J-P",
    title: "Cloud Architecture and Protocols (Lab)",
    credits: 0,
    ciaMax: 60,
    type: "attend-only",
    conducted: 28,
    absent: 0,
    components: [],
  },
];

const user2Subjects: Subject[] = [
  {
    code: "21CSE372P",
    title: "Mastering Cloud Data Services and Analytics with AWS, Azure, and GCP",
    credits: 3,
    ciaMax: 100,
    type: "graded",
    conducted: 47,
    absent: 1,
    components: [
      { name: "FP-I", obtained: 7.4, max: 10 },
      { name: "PBL-I", obtained: 19.5, max: 20 },
      { name: "PBL-II", obtained: 20.0, max: 20 },
    ],
  },
  {
    code: "21CSC303J",
    title: "Software Engineering and Project Management",
    credits: 3,
    ciaMax: 60,
    type: "graded",
    conducted: 38,
    absent: 6,
    components: [
      { name: "FJ-I", obtained: 10.0, max: 15 },
      { name: "FJ-II", obtained: 12.67, max: 15 },
      { name: "FJ-III", obtained: 0.0, max: 15 },
      { name: "LLJ-I", obtained: 6.83, max: 7 },
    ],
  },
  {
    code: "21CSC316J",
    title: "Cloud Architecture and Protocols",
    credits: 3,
    ciaMax: 60,
    type: "graded",
    conducted: 38,
    absent: 2,
    components: [
      { name: "FJ-I", obtained: 11.0, max: 15 },
      { name: "FJ-II", obtained: 10.0, max: 15 },
      { name: "LLJ-I", obtained: 6.9, max: 7 },
    ],
  },
  {
    code: "21IPE317J",
    title: "Advanced AI Cinematics and Virtual Production Engineering",
    credits: 3,
    ciaMax: 60,
    type: "graded",
    conducted: 16,
    absent: 2,
    components: [
      { name: "FJ-I", obtained: 13.5, max: 15 },
      { name: "FJ-II", obtained: 13.5, max: 15 },
      { name: "LLJ-I", obtained: 5.4, max: 7 },
    ],
  },
  {
    code: "21CSS303T",
    title: "Data Science",
    credits: 2,
    ciaMax: 60,
    type: "graded",
    conducted: 26,
    absent: 0,
    components: [
      { name: "FT-I", obtained: 4.5, max: 5 },
      { name: "FT-II", obtained: 12.3, max: 15 },
      { name: "FT-III", obtained: 15.0, max: 15 },
    ],
  },
  {
    code: "21ECO101T",
    title: "Short-Range Wireless Communication",
    credits: 3,
    ciaMax: 60,
    type: "graded",
    conducted: 39,
    absent: 4,
    components: [
      { name: "FT-I", obtained: 5.0, max: 5 },
      { name: "FT-II", obtained: 6.75, max: 15 },
      { name: "FT-III", obtained: 14.4, max: 15 },
    ],
  },
  {
    code: "21LEM302T",
    title: "Indian Traditional Knowledge",
    credits: 0,
    ciaMax: 100,
    type: "graded",
    conducted: 6,
    absent: 0,
    components: [
      { name: "FML-I", obtained: 30.0, max: 30 },
      { name: "FML-II", obtained: 28.0, max: 30 },
    ],
  },
  {
    code: "21CSP302L",
    title: "Project",
    credits: 3,
    ciaMax: 100,
    type: "graded",
    conducted: 20,
    absent: 2,
    components: [
      { name: "R-I", obtained: 28.0, max: 30 },
      { name: "R-II", obtained: 40.0, max: 40 },
    ],
  },
  {
    code: "21IPE317J-P",
    title: "Advanced AI Cinematics and Virtual Production Engineering (Lab)",
    credits: 0,
    ciaMax: 60,
    type: "attend-only",
    conducted: 22,
    absent: 2,
    components: [],
  },
  {
    code: "21CSC303J-P",
    title: "Software Engineering and Project Management (Lab)",
    credits: 0,
    ciaMax: 60,
    type: "attend-only",
    conducted: 26,
    absent: 2,
    components: [],
  },
  {
    code: "21CSC316J-P",
    title: "Cloud Architecture and Protocols (Lab)",
    credits: 0,
    ciaMax: 60,
    type: "attend-only",
    conducted: 28,
    absent: 0,
    components: [],
  },
];

export const DEFAULT_DATA: UserData = {
  user1: user1Subjects,
  user2: user2Subjects,
};
